name: "GoReleaser"

on:
  push:
  workflow_dispatch:


jobs:
  mage-test:
    name: "Mage Test: ${{ matrix.os }}"
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version: ^1
      id: go

    - name: Run Mage
      uses: magefile/mage-action@v3
